version: "3"
services:
  backend:
    build: api
    environment:
      ORIGIN_PORT: "8080"
    ports:
      - 3000:3000
  frontend:
    build: client
    environment:
      PORT: "8080"
    ports:
      - 8080:8080
