version: "3"
services:
  backend:
    build: api
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/chit-chat"
      PORT: "3000"
    ports:
      - 3000:3000
  frontend:
    build: client
    environment:
      VUE_APP_API_URL: "http://localhost:3000"
      PORT: "8080"
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    ports:
      - 27017:27017
